# Generated by Django 3.1.4 on 2021-06-27 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20210627_0652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='userprofile',
            new_name='organization',
        ),
    ]
